// client/src/views/Reminders.vue
<template>
  <div class="page-container page-frame">
    <!-- 页头固定(应用化骨架),仅下方列表滚动 -->
    <van-nav-bar title="提醒" />

    <van-tabs v-model:active="activeTab">
      <van-tab title="待提醒" name="pending" />
      <van-tab title="已提醒" name="done" />
      <van-tab title="全部" name="" />
    </van-tabs>

    <div class="page-content scroll-area">
      <!-- 首次加载骨架:与提醒行对应(标题/车牌日期/类型徽章) -->
      <div v-if="loading">
        <div class="sk-cell" v-for="i in 7" :key="'sk' + i">
          <div class="flex-between">
            <div style="flex: 1">
              <div class="sk sk-line" style="width: 44%"></div>
              <div class="sk sk-sm" style="width: 56%; margin-top: 8px"></div>
            </div>
            <div class="sk sk-pill"></div>
          </div>
        </div>
      </div>
      <template v-if="!loading">
      <van-cell
        v-for="item in reminders"
        :key="item.id"
        :title="item.content || getTypeLabel(item.type)"
        :label="`${item.vehicle?.plateNumber || ''} · 建议 ${formatDate(item.remindDate)}`"
        is-link
        @click="showDetail(item)"
      >
        <template #right-icon>
          <van-tag :type="item.type === 'maintenance' ? 'warning' : 'primary'" >
            {{ getTypeLabel(item.type) }}
          </van-tag>
        </template>
      </van-cell>

      <van-empty v-if="reminders.length === 0" description="暂无提醒" />
      </template>
    </div>

    <!-- 提醒详情弹窗 -->
    <van-popup v-model:show="showDetailPopup" position="bottom" round>
      <div class="popup-content" v-if="current">
        <h3>{{ getTypeLabel(current.type) }}</h3>
        <van-cell title="车辆" :value="current.vehicle?.plateNumber || '-'" />
        <van-cell title="建议日期" :value="formatDate(current.remindDate)" />
        <van-cell title="内容" :value="current.content || '-'" />
        <van-cell title="状态" :value="current.status === 'done' ? '已提醒' : '待提醒'" />
        <van-cell v-if="current.remindedAt" title="提醒时间" :value="formatDateTime(current.remindedAt)" />
        <van-cell v-if="current.feedback" title="客户反馈" :value="current.feedback" />

        <!-- 标记已提醒需记录方式与客户反馈（DESIGN.md 要求） -->
        <template v-if="current.status === 'pending'">
          <van-field name="remindMethod" label="提醒方式" class="mt-12">
            <template #input>
              <van-radio-group v-model="doneForm.method" direction="horizontal">
                <van-radio name="phone">电话</van-radio>
                <van-radio name="wechat">微信</van-radio>
              </van-radio-group>
            </template>
          </van-field>
          <van-field
            v-model="doneForm.feedback"
            label="客户反馈"
            type="textarea"
            rows="2"
            placeholder="可选，记录客户回应"
          />
          <van-button type="primary" block class="mt-16" :loading="marking" @click="markDone">
            标记已提醒
          </van-button>
        </template>
      </div>
    </van-popup>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, watch } from 'vue'
import { showToast } from 'vant'
import { getReminders, updateReminder } from '@/api'
import dayjs from 'dayjs'

const activeTab = ref('pending')
const reminders = ref<any[]>([])
// 首次/切 tab 加载中状态,驱动骨架屏
const loading = ref(true)
const showDetailPopup = ref(false)
const current = ref<any>(null)
// 标记已提醒的补充信息
const doneForm = reactive({ method: 'wechat', feedback: '' })
// 标记中状态：防弱网双击重复提交
const marking = ref(false)

// 提醒类型标签（含挂账交车自动生成的催收提醒）
const getTypeLabel = (t: string) =>
  ({ maintenance: '保养提醒', follow_up: '回访提醒', collection: '催收提醒' } as Record<string, string>)[t] || '提醒'
const formatDate = (d: string) => dayjs(d).format('YYYY-MM-DD')
const formatDateTime = (d: string) => dayjs(d).format('YYYY-MM-DD HH:mm')

const loadData = async () => {
  loading.value = true
  try {
    const params: any = {}
    if (activeTab.value) params.status = activeTab.value
    const data = await getReminders(params)
    reminders.value = data as any[]
  } catch (e) {
    // 静默
  } finally {
    loading.value = false
  }
}

const showDetail = (item: any) => {
  current.value = item
  // 打开新条目时重置待填项，避免上一条的反馈串到下一条
  doneForm.method = 'wechat'
  doneForm.feedback = ''
  showDetailPopup.value = true
}

const markDone = async () => {
  if (!current.value || marking.value) return
  marking.value = true
  try {
    const payload: any = {
      status: 'done',
      remindedAt: new Date().toISOString(),
      remindMethod: doneForm.method
    }
    // 反馈选填，未填写则不更新该字段
    if (doneForm.feedback) payload.feedback = doneForm.feedback
    await updateReminder(current.value.id, payload)
    showToast({ type: 'success', message: '已标记' })
    showDetailPopup.value = false
    loadData()
  } catch (e) {
    // 已拦截
  } finally {
    marking.value = false
  }
}

watch(activeTab, loadData)
onMounted(loadData)
</script>

<style scoped>
/* 首次加载骨架行:与提醒 cell 的信息结构对应 */
.sk-cell {
  padding: 13px 4px;
  border-bottom: 1px solid var(--hairline);
}
.popup-content {
  padding: 20px 16px 32px;
}
.popup-content h3 {
  text-align: center;
  margin-bottom: 12px;
}
</style>

// web/src/app/(tabs)/reminders/page.tsx
'use client'

// 提醒列表：3 状态 tabs + 详情弹窗 + 标记已提醒（自旧 Reminders.vue 移植）
import { useCallback, useEffect, useState } from 'react'
import { toast } from 'sonner'
import NavBar from '@/components/mobile/NavBar'
import Cell from '@/components/mobile/Cell'
import Empty from '@/components/mobile/Empty'
import BottomSheet from '@/components/mobile/BottomSheet'
import Field from '@/components/mobile/Field'
import ScrollTabs from '@/components/mobile/ScrollTabs'
import { Badge } from '@/components/mobile/Badge'
import { Textarea } from '@/components/ui/textarea'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { getReminders, updateReminder } from '@/lib/api'
import { getReminderTypeLabel, formatDate, formatDateTime } from '@/lib/format'

const TABS = [
  { label: '待提醒', value: 'pending' },
  { label: '已提醒', value: 'done' },
  { label: '全部', value: '' }
]

export default function RemindersPage() {
  const [activeTab, setActiveTab] = useState('pending')
  const [reminders, setReminders] = useState<any[]>([])
  // 首次/切 tab 加载中状态，驱动骨架屏
  const [loading, setLoading] = useState(true)
  const [showDetail, setShowDetail] = useState(false)
  const [current, setCurrent] = useState<any>(null)
  // 标记已提醒的补充信息
  const [doneForm, setDoneForm] = useState({ method: 'wechat', feedback: '' })
  // 标记中状态：防弱网双击重复提交
  const [marking, setMarking] = useState(false)

  const loadData = useCallback(async () => {
    setLoading(true)
    try {
      const params: Record<string, string> = {}
      if (activeTab) params.status = activeTab
      const data = await getReminders(params)
      setReminders(data as any[])
    } catch { /* 静默 */ } finally {
      setLoading(false)
    }
  }, [activeTab])

  useEffect(() => { void loadData() }, [loadData])

  const openDetail = (item: any) => {
    setCurrent(item)
    // 打开新条目时重置待填项，避免上一条的反馈串到下一条
    setDoneForm({ method: 'wechat', feedback: '' })
    setShowDetail(true)
  }

  const markDone = async () => {
    if (!current || marking) return
    setMarking(true)
    try {
      const payload: Record<string, unknown> = {
        status: 'done',
        remindedAt: new Date().toISOString(),
        remindMethod: doneForm.method
      }
      // 反馈选填，未填写则不更新该字段
      if (doneForm.feedback) payload.feedback = doneForm.feedback
      await updateReminder(current.id, payload)
      toast.success('已标记')
      setShowDetail(false)
      void loadData()
    } catch { /* 已拦截 */ } finally {
      setMarking(false)
    }
  }

  return (
    <div className="page-container page-frame">
      <NavBar title="提醒" back={false} />
      <ScrollTabs tabs={TABS} value={activeTab} onChange={setActiveTab} />

      <div className="page-content scroll-area">
        {/* 首次加载骨架：与提醒行信息结构对应 */}
        {loading &&
          Array.from({ length: 7 }, (_, i) => (
            <div key={i} className="border-b py-[13px]" style={{ borderColor: 'var(--hairline)' }}>
              <div className="flex-between">
                <div className="flex-1">
                  <div className="sk sk-line" style={{ width: '44%' }} />
                  <div className="sk sk-sm" style={{ width: '56%', marginTop: 8 }} />
                </div>
                <div className="sk sk-pill" />
              </div>
            </div>
          ))}

        {!loading && (
          <>
            {reminders.map(item => (
              <Cell
                key={item.id}
                title={item.content || getReminderTypeLabel(item.type)}
                label={`${item.vehicle?.plateNumber ?? ''} · 建议 ${formatDate(item.remindDate)}`}
                right={
                  <Badge tone={item.type === 'maintenance' ? 'warning' : 'primary'}>
                    {getReminderTypeLabel(item.type)}
                  </Badge>
                }
                onClick={() => openDetail(item)}
              />
            ))}
            {reminders.length === 0 && <Empty description="暂无提醒" />}
          </>
        )}
      </div>

      {/* 提醒详情弹窗 */}
      <BottomSheet open={showDetail} onOpenChange={setShowDetail} title={current ? getReminderTypeLabel(current.type) : ''}>
        {current && (
          <div className="flex flex-col gap-2">
            <Cell title="车辆" right={<span style={{ color: 'var(--ink)' }}>{current.vehicle?.plateNumber || '-'}</span>} />
            <Cell title="建议日期" right={<span style={{ color: 'var(--ink)' }}>{formatDate(current.remindDate)}</span>} />
            <Cell title="内容" right={<span style={{ color: 'var(--ink)' }}>{current.content || '-'}</span>} />
            <Cell title="状态" right={<span style={{ color: 'var(--ink)' }}>{current.status === 'done' ? '已提醒' : '待提醒'}</span>} />
            {current.remindedAt && (
              <Cell title="提醒时间" right={<span style={{ color: 'var(--ink)' }}>{formatDateTime(current.remindedAt)}</span>} />
            )}
            {current.feedback && (
              <Cell title="客户反馈" right={<span style={{ color: 'var(--ink)' }}>{current.feedback}</span>} />
            )}

            {/* 标记已提醒需记录方式与客户反馈（DESIGN.md 要求） */}
            {current.status === 'pending' && (
              <div className="mt-3 flex flex-col gap-3">
                <Field label="提醒方式">
                  <RadioGroup
                    value={doneForm.method}
                    onValueChange={v => setDoneForm(f => ({ ...f, method: v }))}
                    className="flex gap-5"
                  >
                    <Label className="flex items-center gap-2 text-[14px] font-normal" style={{ color: 'var(--ink)' }}>
                      <RadioGroupItem value="phone" /> 电话
                    </Label>
                    <Label className="flex items-center gap-2 text-[14px] font-normal" style={{ color: 'var(--ink)' }}>
                      <RadioGroupItem value="wechat" /> 微信
                    </Label>
                  </RadioGroup>
                </Field>
                <Field label="客户反馈">
                  <Textarea
                    rows={2}
                    value={doneForm.feedback}
                    placeholder="可选，记录客户回应"
                    onChange={e => setDoneForm(f => ({ ...f, feedback: e.target.value }))}
                  />
                </Field>
                <Button className="mt-1 h-10" disabled={marking} onClick={markDone}>标记已提醒</Button>
              </div>
            )}
          </div>
        )}
      </BottomSheet>
    </div>
  )
}
