// web/src/app/(tabs)/customers/page.tsx
'use client'

// 客户列表：搜索 + 新增客户弹窗（自旧 Customers.vue 移植）
import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AnimatePresence, motion } from 'motion/react'
import { toast } from 'sonner'
import { Plus } from 'lucide-react'
import NavBar from '@/components/mobile/NavBar'
import Cell from '@/components/mobile/Cell'
import Empty from '@/components/mobile/Empty'
import BottomSheet from '@/components/mobile/BottomSheet'
import Field from '@/components/mobile/Field'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import { Search } from 'lucide-react'
import { getCustomers, createCustomer } from '@/lib/api'

export default function CustomersPage() {
  const router = useRouter()

  const [customers, setCustomers] = useState<any[]>([])
  const [keyword, setKeyword] = useState('')
  const [loading, setLoading] = useState(false)
  const [showAdd, setShowAdd] = useState(false)
  const [form, setForm] = useState({ name: '', phone: '', remark: '' })
  // 保存中状态：防弱网双击重复建档
  const [adding, setAdding] = useState(false)

  const loadData = useCallback(async () => {
    setLoading(true)
    try {
      const data = await getCustomers({ keyword })
      setCustomers(data as any[])
    } catch { /* 静默 */ } finally {
      setLoading(false)
    }
  }, [keyword])

  useEffect(() => { void loadData() }, [loadData])

  const submitAdd = async () => {
    if (adding) return
    if (!form.name) return toast('请输入姓名')
    if (!form.phone) return toast('请输入电话')
    setAdding(true)
    try {
      await createCustomer(form)
      toast.success('添加成功')
      setShowAdd(false)
      setForm({ name: '', phone: '', remark: '' })
      void loadData()
    } catch { /* 已拦截 */ } finally {
      setAdding(false)
    }
  }

  return (
    <div className="page-container page-frame">
      <NavBar
        title="客户"
        back={false}
        right={
          <button type="button" aria-label="新增客户" className="pressable" onClick={() => setShowAdd(true)}>
            <Plus size={20} />
          </button>
        }
      />

      {/* 搜索框 */}
      <div className="flex items-center px-3 py-2">
        <div className="relative flex-1">
          <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: 'var(--ink-tertiary)' }} />
          <Input
            value={keyword}
            placeholder="搜索姓名/电话"
            className="h-9 rounded-lg pl-8"
            style={{ background: 'var(--surface-2)' }}
            onChange={e => setKeyword(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter') void loadData() }}
          />
        </div>
      </div>

      <div className="page-content scroll-area">
        {/* 首次加载骨架：与客户行信息结构对应 */}
        {loading && customers.length === 0 &&
          Array.from({ length: 7 }, (_, i) => (
            <div key={i} className="border-b py-[13px]" style={{ borderColor: 'var(--hairline)' }}>
              <div className="flex-between">
                <div className="flex-1">
                  <div className="sk sk-line" style={{ width: '26%' }} />
                  <div className="sk sk-sm" style={{ width: '40%', marginTop: 8 }} />
                </div>
                <div className="sk sk-sm" style={{ width: 42 }} />
              </div>
            </div>
          ))}

        <AnimatePresence initial={false}>
          {customers.map((c, idx) => (
            <motion.div
              key={c.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6, transition: { duration: 0.15 } }}
              transition={{ type: 'spring', bounce: 0, duration: 0.35, delay: Math.min(idx * 0.03, 0.24) }}
            >
              <Cell
                title={c.name}
                label={c.phone}
                right={<span>{c._count?.vehicles || 0}辆车</span>}
                onClick={() => router.push(`/customers/${c.id}`)}
              />
            </motion.div>
          ))}
        </AnimatePresence>

        {customers.length === 0 && !loading && <Empty description="暂无客户" />}
      </div>

      {/* 新增客户弹窗 */}
      <BottomSheet open={showAdd} onOpenChange={setShowAdd} title="新增客户">
        <div className="flex flex-col gap-3">
          <Field label="姓名">
            <Input value={form.name} placeholder="请输入姓名" onChange={e => setForm(f => ({ ...f, name: e.target.value }))} />
          </Field>
          <Field label="电话">
            <Input type="tel" value={form.phone} placeholder="请输入电话" onChange={e => setForm(f => ({ ...f, phone: e.target.value }))} />
          </Field>
          <Field label="备注">
            <Textarea rows={2} value={form.remark} placeholder="可选" onChange={e => setForm(f => ({ ...f, remark: e.target.value }))} />
          </Field>
          <Button className="mt-2 h-10" disabled={adding} onClick={submitAdd}>保存</Button>
        </div>
      </BottomSheet>
    </div>
  )
}

// client/src/views/Customers.vue
<template>
  <div class="page-container page-frame">
    <!-- 页头固定(应用化骨架),仅下方列表滚动 -->
    <van-nav-bar title="客户">
      <template #right>
        <van-icon name="add" size="20" @click="showAdd = true" />
      </template>
    </van-nav-bar>

    <van-search v-model="keyword" placeholder="搜索姓名/电话" @search="onSearch" />

    <div class="page-content scroll-area">
      <!-- 首次加载骨架:与客户行对应(姓名/电话/车辆数) -->
      <div v-if="loading && customers.length === 0">
        <div class="sk-cell" v-for="i in 7" :key="'sk' + i">
          <div class="flex-between">
            <div style="flex: 1">
              <div class="sk sk-line" style="width: 26%"></div>
              <div class="sk sk-sm" style="width: 40%; margin-top: 8px"></div>
            </div>
            <div class="sk sk-sm" style="width: 42px"></div>
          </div>
        </div>
      </div>
      <!-- 列表项进场：弹簧上移淡入，逐项错开形成级联；AnimatePresence 让搜索换批时旧项平滑退场 -->
      <AnimatePresence>
        <motion.div
          v-for="(c, idx) in customers"
          :key="c.id"
          :initial="{ opacity: 0, y: 10 }"
          :animate="{ opacity: 1, y: 0 }"
          :exit="{ opacity: 0, y: -6, transition: { duration: 0.15 } }"
          :transition="{ type: 'spring', bounce: 0, duration: 0.35, delay: Math.min(idx * 0.03, 0.24) }"
        >
          <van-cell
            :title="c.name"
            :label="c.phone"
            is-link
            @click="$router.push(`/customers/${c.id}`)"
          >
            <template #right-icon>
              <span class="text-muted">{{ c._count?.vehicles || 0 }}辆车</span>
            </template>
          </van-cell>
        </motion.div>
      </AnimatePresence>

      <van-empty v-if="customers.length === 0 && !loading" description="暂无客户" />
    </div>

    <!-- 新增客户弹窗 -->
    <van-popup v-model:show="showAdd" position="bottom" round>
      <div class="popup-content">
        <h3>新增客户</h3>
        <van-field v-model="form.name" label="姓名" placeholder="请输入姓名" />
        <van-field v-model="form.phone" label="电话" placeholder="请输入电话" type="tel" />
        <van-field v-model="form.remark" label="备注" placeholder="可选" type="textarea" rows="2" />
        <van-button type="primary" block class="mt-16" :loading="adding" @click="submitAdd">保存</van-button>
      </div>
    </van-popup>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, reactive } from 'vue'
import { showToast } from 'vant'
import { motion, AnimatePresence } from 'motion-v'
import { getCustomers, createCustomer } from '@/api'

const customers = ref<any[]>([])
const keyword = ref('')
const loading = ref(false)
const showAdd = ref(false)
const form = reactive({ name: '', phone: '', remark: '' })
// 保存中状态：防弱网双击重复建档
const adding = ref(false)

const loadData = async () => {
  loading.value = true
  try {
    const data = await getCustomers({ keyword: keyword.value })
    customers.value = data as any[]
  } catch (e) {
    // 静默
  } finally {
    loading.value = false
  }
}

const onSearch = () => loadData()

const submitAdd = async () => {
  if (adding.value) return
  if (!form.name) return showToast('请输入姓名')
  if (!form.phone) return showToast('请输入电话')
  adding.value = true
  try {
    await createCustomer(form)
    showToast({ type: 'success', message: '添加成功' })
    showAdd.value = false
    form.name = ''
    form.phone = ''
    form.remark = ''
    loadData()
  } catch (e) {
    // 已拦截
  } finally {
    adding.value = false
  }
}

onMounted(loadData)
</script>

<style scoped>
/* 首次加载骨架行:与客户 cell 的信息结构对应 */
.sk-cell {
  padding: 13px 4px;
  border-bottom: 1px solid var(--hairline);
}
.popup-content {
  padding: 20px 16px 32px;
}
.popup-content h3 {
  text-align: center;
  margin-bottom: 16px;
}
</style>
