// web/src/components/PlateKeyboard.tsx
'use client'

// 车牌专用键盘：省份简称 → 字母 → 字母数字逐段切换，杜绝系统键盘中英切换与脏字符
// （自旧 client/src/components/PlateKeyboard.vue 移植，弹层改用 BottomSheet）
import { useEffect, useState } from 'react'
import BottomSheet from '@/components/mobile/BottomSheet'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import {
  PROVINCES, PLATE_LETTERS, PLATE_ALNUM,
  PLATE_NORMAL_LEN, PLATE_NE_LEN
} from '@/lib/plate'
import { cn } from '@/lib/utils'

interface PlateKeyboardProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  value: string
  onChange: (value: string) => void
}

export default function PlateKeyboard({ open, onOpenChange, value, onChange }: PlateKeyboardProps) {
  // 新能源标记：8 位已达上限时自动勾上（从 OCR/手输回填的场景）
  const [isNewEnergy, setIsNewEnergy] = useState(false)

  // 打开时按现有值长度初始化新能源态
  useEffect(() => {
    if (open) setIsNewEnergy(value.length > PLATE_NORMAL_LEN)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // 取消新能源时截断超出的第 8 位
  useEffect(() => {
    if (!isNewEnergy && value.length > PLATE_NORMAL_LEN) {
      onChange(value.slice(0, PLATE_NORMAL_LEN))
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isNewEnergy])

  const cellCount = isNewEnergy ? PLATE_NE_LEN : PLATE_NORMAL_LEN
  const reachedLimit = value.length >= cellCount

  // 按键输入（达上限后忽略）
  const press = (ch: string) => {
    if (reachedLimit) return
    onChange(value + ch)
  }

  const keys = value.length === 0 ? PROVINCES : value.length === 1 ? PLATE_LETTERS : PLATE_ALNUM

  return (
    <BottomSheet open={open} onOpenChange={onOpenChange}>
      <div className="pb-1">
        {/* 预览区：格子化展示当前输入 */}
        <div className="mb-3.5 flex items-center justify-between gap-3">
          <div className="flex flex-1 gap-1">
            {Array.from({ length: cellCount }, (_, i) => (
              <div
                key={i}
                className={cn(
                  'flex h-[38px] flex-1 items-center justify-center rounded-md border font-mono text-[17px] font-semibold',
                  i < value.length ? 'border-[var(--primary)] bg-[var(--primary)] text-white' : 'border-[var(--hairline-strong)] bg-[var(--surface-1)] text-[var(--ink)]',
                  i === value.length && 'border-[var(--primary-hover)]'
                )}
              >
                {value[i] || ''}
              </div>
            ))}
          </div>
          <label className="flex shrink-0 items-center gap-1.5 text-[13px]" style={{ color: 'var(--ink-muted)' }}>
            <Checkbox
              checked={isNewEnergy}
              onCheckedChange={v => setIsNewEnergy(!!v)}
              className="h-3.5 w-3.5"
            />
            新能源
          </label>
        </div>

        {/* 键盘面板：按已输入长度自动切换段位（省份网格 / 字母 / 字母数字） */}
        <div className="grid grid-cols-9 gap-1.5">
          {keys.map(k => (
            <button
              key={k}
              type="button"
              className="pressable h-[42px] rounded-lg border font-mono text-[16px]"
              style={{
                borderColor: 'var(--hairline)',
                background: 'var(--surface-1)',
                color: 'var(--ink-muted)'
              }}
              disabled={value.length !== 0 && reachedLimit}
              onClick={() => press(k)}
            >
              {k}
            </button>
          ))}
        </div>

        {/* 功能键行 */}
        <div className="mt-3 flex justify-end gap-2">
          <Button variant="outline" size="sm" onClick={() => onChange(value.slice(0, -1))}>删格</Button>
          <Button variant="outline" size="sm" onClick={() => onChange('')}>清空</Button>
          <Button size="sm" onClick={() => onOpenChange(false)}>完成</Button>
        </div>
      </div>
    </BottomSheet>
  )
}

// client/src/components/PlateKeyboard.vue
<!-- 车牌专用键盘：省份简称 → 字母 → 字母数字逐段切换，杜绝系统键盘中英切换与脏字符 -->
<template>
  <van-popup
    :show="show"
    position="bottom"
    round
    @update:show="(v: boolean) => emit('update:show', v)"
  >
    <div class="plate-kb">
      <!-- 预览区：格子化展示当前输入 -->
      <div class="kb-header">
        <div class="cells" :class="{ ne: isNewEnergy }">
          <div
            v-for="i in cellCount"
            :key="i"
            class="cell"
            :class="{ filled: i <= modelValue.length, cursor: i === modelValue.length + 1 }"
          >
            {{ modelValue[i - 1] || '' }}
          </div>
        </div>
        <div class="header-ops">
          <van-checkbox v-model="isNewEnergy" shape="square" icon-size="14px">新能源</van-checkbox>
        </div>
      </div>

      <!-- 键盘面板：按已输入长度自动切换段位 -->
      <div class="kb-panel">
        <!-- 第 1 位：省份网格 -->
        <template v-if="modelValue.length === 0">
          <button
            v-for="p in PROVINCES"
            :key="p"
            class="key province pressable"
            type="button"
            @click="press(p)"
          >{{ p }}</button>
        </template>
        <!-- 第 2 位：字母 -->
        <template v-else-if="modelValue.length === 1">
          <button
            v-for="k in PLATE_LETTERS"
            :key="k"
            class="key pressable"
            type="button"
            :disabled="reachedLimit"
            @click="press(k)"
          >{{ k }}</button>
        </template>
        <!-- 后段：字母数字混合 -->
        <template v-else>
          <button
            v-for="k in PLATE_ALNUM"
            :key="k"
            class="key alnum pressable"
            type="button"
            :disabled="reachedLimit"
            @click="press(k)"
          >{{ k }}</button>
        </template>
      </div>

      <!-- 功能键行 -->
      <div class="kb-actions">
        <van-button size="small" plain @click="backspace">删格</van-button>
        <van-button size="small" plain @click="clearAll">清空</van-button>
        <van-button size="small" type="primary" @click="finish">完成</van-button>
      </div>
    </div>
  </van-popup>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import {
  PROVINCES, PLATE_LETTERS, PLATE_ALNUM,
  PLATE_NORMAL_LEN, PLATE_NE_LEN
} from '@/utils/plate'

const props = defineProps<{
  show: boolean
  modelValue: string
}>()

const emit = defineEmits<{
  (e: 'update:show', v: boolean): void
  (e: 'update:modelValue', v: string): void
}>()

// 新能源标记：8 位已达上限时自动勾上（从 OCR/手输回填的场景）
const isNewEnergy = ref(false)

const cellCount = computed(() => (isNewEnergy.value ? PLATE_NE_LEN : PLATE_NORMAL_LEN))
const reachedLimit = computed(() => props.modelValue.length >= cellCount.value)

// 打开时按现有值长度初始化新能源态；关闭切换截断超出部分
watch(
  () => props.show,
  (open) => {
    if (open) {
      isNewEnergy.value = props.modelValue.length > PLATE_NORMAL_LEN
    }
  }
)
watch(isNewEnergy, (ne) => {
  if (!ne && props.modelValue.length > PLATE_NORMAL_LEN) {
    emit('update:modelValue', props.modelValue.slice(0, PLATE_NORMAL_LEN))
  }
})

// 按键输入（达上限后忽略）
const press = (ch: string) => {
  if (reachedLimit.value) return
  emit('update:modelValue', props.modelValue + ch)
}

// 删除最后一位
const backspace = () => {
  emit('update:modelValue', props.modelValue.slice(0, -1))
}

// 清空后回到省份面板
const clearAll = () => {
  emit('update:modelValue', '')
}

// 完成：格式不对也允许关闭，由表单提交时统一校验提示
const finish = () => {
  emit('update:show', false)
}
</script>

<style scoped>
.plate-kb {
  padding: 16px 12px calc(16px + env(safe-area-inset-bottom));
}
/* 预览格子 */
.kb-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 14px;
}
.cells {
  display: flex;
  gap: 4px;
  flex: 1;
}
.cell {
  flex: 1;
  height: 38px;
  border: 1px solid var(--hairline-strong);
  border-radius: 6px;
  background: var(--surface-1);
  color: var(--ink);
  font-family: var(--font-mono);
  font-size: 17px;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
}
.cell.filled {
  background: var(--primary);
  border-color: var(--primary);
  color: #fff;
}
.cell.cursor {
  border-color: var(--primary-hover);
}
.header-ops {
  flex-shrink: 0;
}
/* 键盘网格 */
.kb-panel {
  display: grid;
  grid-template-columns: repeat(9, 1fr);
  gap: 6px;
}
.key {
  height: 42px;
  border: 1px solid var(--hairline);
  border-radius: 8px;
  background: var(--surface-1);
  color: var(--ink-muted);
  font-size: 16px;
  font-family: var(--font-mono);
  cursor: pointer;
  user-select: none;
}
.key:active {
  background: var(--surface-2);
  color: var(--ink);
}
.key:disabled {
  opacity: 0.35;
  cursor: default;
}
/* 功能键行 */
.kb-actions {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  margin-top: 12px;
}
</style>
